<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <title>Appointment Invoice</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #222;
        }

        .header {
            text-align: center;
            margin-bottom: 25px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0;
            color: #666;
        }

        .invoice-info {
            width: 100%;
            margin-bottom: 20px;
        }

        .invoice-info td {
            padding: 5px;
        }

        .section {
            margin-top: 20px;
            margin-bottom: 10px;
            font-size: 14px;
            font-weight: bold;
        }

        table.items {
            width: 100%;
            border-collapse: collapse;
        }

        table.items th,
        table.items td {
            border: 1px solid #ddd;
            padding: 9px;
        }

        table.items th {
            background: #f4f4f4;
            text-align: left;
        }

        .total {
            margin-top: 15px;
            width: 100%;
            text-align: right;
        }

        .total td {
            padding: 6px;
        }

        .grand-total {
            font-size: 17px;
            font-weight: bold;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            color: #777;
            font-size: 10px;
        }
    </style>
</head>

<body>

<div class="header">
    <h1>APPOINTMENT INVOICE</h1>
    <p>Ayu System</p>
</div>

<table class="invoice-info">
    <tr>
        <td>
            <strong>Invoice No:</strong>
            {{ $appointment->invoice_number }}
        </td>

        <td>
            <strong>Date:</strong>
            {{ optional($appointment->invoice_issued_at)->format('d M Y h:i A') }}
        </td>
    </tr>

    <tr>
        <td>
            <strong>Booking No:</strong>
            {{ $appointment->booking_number }}
        </td>

        <td>
            <strong>Status:</strong>
            {{ ucfirst($appointment->payment_status ?? 'unpaid') }}
        </td>
    </tr>
</table>

<div class="section">
    Patient Details
</div>

<table class="invoice-info">
    <tr>
        <td>
            <strong>Name:</strong>
            {{ $appointment->full_name }}
        </td>
    </tr>

    <tr>
        <td>
            <strong>NIC / Passport:</strong>
            {{ $appointment->nic_or_passport }}
        </td>
    </tr>

    <tr>
        <td>
            <strong>Phone:</strong>
            {{ $appointment->phone_number }}
        </td>
    </tr>
</table>

<div class="section">
    Appointment Details
</div>

<table class="items">
    <thead>
        <tr>
            <th>Doctor</th>
            <th>Room</th>
            <th>Date & Time</th>
            <th>Doctor Fee</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                {{ $appointment->doctor?->name ?? 'N/A' }}
            </td>

            <td>
                {{ $appointment->doctor?->room_number
                    ? 'Room ' . $appointment->doctor->room_number
                    : 'Not Assigned' }}
            </td>

            <td>
                {{ optional($appointment->appointment_date)->format('d M Y, h:i A') }}
            </td>

            <td>
                {{ $appointment->invoice_currency }}
                {{ number_format((float) $appointment->appointment_fee, 2) }}
            </td>
        </tr>
    </tbody>
</table>

<table class="total">
    <tr>
    <td>
        <strong>Facilities / Service Fee:</strong>
    </td>
    <td>
        {{ $appointment->invoice_currency }}
        {{ number_format((float) $appointment->facility_service_fee, 2) }}
    </td>
    </tr>
    <tr>
    <td>
        <strong>Total:</strong>
    </td>
    <td class="grand-total">
        {{ $appointment->invoice_currency }}
        {{ number_format((float) $appointment->invoice_total, 2) }}
    </td>
    </tr>
</table>

<div class="footer">
    Appointment invoice generated by Ayu System.
</div>

</body>
</html>
